@startuml
class Animal {
  - petStatus: String
  - hungry: int
  - affection: int
  - catState: CatState

  + displayInfo(): void
  + eat(): void
  + sleep(): void
  + play(): void
}

enum CatState {
  Awake
  Sleeping
}

class Cat {
  - myPet: Animal
  - currentImage: String
  - hungerTimer: Timer?
  - interactionCount: int

  + initState(): void
  + dispose(): void
  + _interactWithPet(): void
  + _feedPet(): void
  + _playWithPet(): void
  + _waitForStatusChange(): void
  + _changeImage(): void
  + _increaseAffection(value: int): void
  + build(context: BuildContext): Widget
}
@enduml
