@startuml
class DiaryScreen {
  - checkBoxValue: bool
  - checkBox2Value: bool
  - checkBox3Value: bool
  - checkBox4Value: bool
  - totalAmount: int
  - today: String

  + initState(): void
  + getDate(): void
  + build(context: BuildContext): Widget
  + calculateTotalAmount(): void
}
@enduml
