@startuml
class MyHomePage {
  - _currentIndex: int
  - _screens: List<Widget>

  + build(context: BuildContext): Widget
}
MyHomePage --> StoreScreen
MyHomePage --> InventoryScreen
MyHomePage --> Cat
MyHomePage --> ChechListScreen
MyHomePage --> DiaryScreen
@enduml
